version: "3.8"

services:
  mssql:
    container_name: spacex-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    build:
      context: ./
      dockerfile: Dockerfile.mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - SQL_SERVER=${SQL_SERVER}
    volumes:
      - spacex-sql-data:/var/opt/mssql
      - ./spacex-db.sql:/data/application/spacex-db.sql
      - ./entrypoint.sh:/entrypoint.sh

  SpacexServer.Api:
    container_name: spacex-server
    image: spacex.api
    build:
      context: ../
      dockerfile: SpacexApp/SpacexServer.Api/Dockerfile
    ports:
      - "7005:7005"
    depends_on:
      - mssql
    environment:
      - SQL_SERVER=${SQL_SERVER}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      
  SpacexServer.Client:
    container_name: spacex-client
    image: spacex.client
    build:
      context: ../SpacexApp/Spacex.Client/spacex-angular
    ports:
      - "4300:4300"
    volumes:
      - ../SpacexApp/Spacex.Client/spacex-angular:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "start"]

volumes:
  spacex-sql-data:
