name: Setup .env file

on: [push, pull_request]

jobs:
  setup-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Current Directory
        run: |
          echo "Current working directory: $(pwd)"
          echo "Listing files in the workspace:"
          ls -la

      - name: Create .env File
        run: |
          touch .env  # Create the file in the default workspace
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "SQL_SERVER=${{ secrets.SQL_SERVER }}" >> .env
          echo ".env file created with the following content:"
          cat .env  # Debugging: Show file content

      - name: Verify .env Exists
        run: |
          if [ -f ".env" ]; then
            echo ".env file exists!"
          else
            echo "ERROR: .env file was not found!"
            exit 1  # Stop workflow if file does not exist
          fi

      - name: Upload .env as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env  # No $GITHUB_WORKSPACE needed
